// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZn1mn_0r51T6HezKfhzsSw18rxYwBodA',
    appId: '1:339271609831:web:3c65ddb82327aac0452142',
    messagingSenderId: '339271609831',
    projectId: 'my-second-own-app',
    authDomain: 'my-second-own-app.firebaseapp.com',
    storageBucket: 'my-second-own-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8nmcXvsLII7nJMei_EUuozceg6IERT04',
    appId: '1:339271609831:android:cf5af8357dfb5c1d452142',
    messagingSenderId: '339271609831',
    projectId: 'my-second-own-app',
    storageBucket: 'my-second-own-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1ZtsqTDIQjOJayOabpIPgaknrYsvfkpE',
    appId: '1:339271609831:ios:a376980ae7e1f691452142',
    messagingSenderId: '339271609831',
    projectId: 'my-second-own-app',
    storageBucket: 'my-second-own-app.appspot.com',
    iosClientId: '339271609831-kgaueao4gthjj4nea4guejrbtid34aiv.apps.googleusercontent.com',
    iosBundleId: 'com.example.secondApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1ZtsqTDIQjOJayOabpIPgaknrYsvfkpE',
    appId: '1:339271609831:ios:a376980ae7e1f691452142',
    messagingSenderId: '339271609831',
    projectId: 'my-second-own-app',
    storageBucket: 'my-second-own-app.appspot.com',
    iosClientId: '339271609831-kgaueao4gthjj4nea4guejrbtid34aiv.apps.googleusercontent.com',
    iosBundleId: 'com.example.secondApp',
  );
}
